Doctors/Models/UserRoles/UserRole.cs
using Doctors.Models.Users;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;

namespace MVC.Models.UserRoles
{
    public class UserRole : IdentityUserRole<string>
    {
        [DisplayName("UserId")]
        public User User { get; set; }
    }
}

Doctors/Controllers/UserRoleController.cs
using Doctors.Data;
using Doctors.ViewModels.UserRoleViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using MVC.DTOs;
using MVC.Models.UserRoles;
using System.Linq;

namespace MVC.Controllers
{
    [Authorize]
    public class UserRoleController : Controller
    {
        private ApplicationDbContext _context;
        public UserRoleController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            UserRolesListViewModel model = new UserRolesListViewModel();

            var userRoles = _context.UserRoles;

            if (userRoles != null)
            {
                var query = (from userRole in _context.UserRoles
                             from user in _context.Users
                             from role in _context.Roles
                             where user.Id == userRole.UserId && role.Id == userRole.RoleId
                             select new UserRoleDto() { UserName = user.UserName, RoleName = role.Name })?.ToList();


                model.UserRoles = query;

            }

            return View("Index", model);
        }


        public IActionResult Add(AddUserRoleViewModel model)
        {

            model.Success = false;

            var users = _context.Users.ToList();
            model.Users = new SelectList(users, "Id", "UserName");

            var roles = _context.Roles.ToList();
            model.Roles = new SelectList(roles, "Id", "Name");

            return View("Add", model);
        }

        [HttpPost]
        public IActionResult Add(string userId, string roleId, AddUserRoleViewModel model)
        {

            var users = _context.Users.ToList();
            model.Users = new SelectList(users, "Id", "UserName");

            var roles = _context.Roles.ToList();
            model.Roles = new SelectList(roles, "Id", "Name");

            if (ModelState.IsValid)
            {

                var exists = _context.UserRoles.FirstOrDefault(x => x.UserId == userId && x.RoleId == roleId);

                if (exists != null)
                {
                    ModelState.AddModelError("", "User role already exists");
                    return View("Add", model);
                }
                else
                {
                    UserRole userRole = new UserRole();

                    userRole.UserId = userId;
                    userRole.RoleId = roleId;

                    _context.UserRoles.Add(userRole);

                    model.Success = true;


                }

                return View("Add", model);
            }


            return View("Add", model);
        }

        public IActionResult Edit(string username, string rolename)
        {
            EditUserRoleViewModel model = new EditUserRoleViewModel();

            model.Success = false;

            var users = _context.Users.ToList();
            model.Users = new SelectList(users, "Id", "UserName");

            var roles = _context.Roles.ToList();
            model.Roles = new SelectList(roles, "Id", "Name");


            return View("Edit", model);
        }

    }
}

Doctors/Views/UserRole/Add.cshtml
@model Doctors.ViewModels.UserRoleViewModels.AddUserRoleViewModel

@{
    ViewData["Title"] = "Add";
}


@{

}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-center">
            @if (Model.Success)
            {
                <div class="alert alert-success">
                    <strong>Success!</strong> User role successfully added!
                </div>
            }
            <h2>@ViewData["Title"]</h2>
            <form method="post" asp-action="Add" asp-controller="UserRole">

                <div class="form-group">
                    <label asp-for="UserId"></label>
                    <select asp-for="UserId" asp-items="@Model.Users" class="form-control"></select>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="RoleId"></label>
                    <select asp-for="RoleId" asp-items="@Model.Roles" class="form-control"></select>
                    <span asp-validation-for="RoleId" class="text-danger"></span>
                </div>


                <div asp-validation-summary="All" class="text-danger"></div>

                <button type="submit" class="btn btn-primary pull-right">Add</button>
                <a class="btn btn-default pull-left" asp-action="Index">Back</a>


            </form>
        </div>
    </div>
</div>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Doctors/Views/UserRole/Edit.cshtml
@model Doctors.ViewModels.UserRoleViewModels.EditUserRoleViewModel

@{
    ViewData["Title"] = "Edit";
}


@{

}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-center">
            @if (Model.Success)
            {
                <div class="alert alert-success">
                    <strong>Success!</strong> User role successfully added!
                </div>
            }
            <h2>@ViewData["Title"]</h2>
            <form method="post" asp-action="Edit" asp-controller="UserRole">

                <div class="form-group">
                    <label asp-for="UserId"></label>
                    <select asp-for="UserId" asp-items="@Model.Users" class="form-control"></select>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="RoleId"></label>
                    <select asp-for="RoleId" asp-items="@Model.Roles" class="form-control"></select>
                    <span asp-validation-for="RoleId" class="text-danger"></span>
                </div>


                <div asp-validation-summary="All" class="text-danger"></div>

                <button type="submit" class="btn btn-primary">Save</button>


            </form>
        </div>
    </div>
</div>


@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Doctors/Views/UserRole/Index.cshtml
@model Doctors.ViewModels.UserRoleViewModels.UserRolesListViewModel

@if (Model.UserRoles.Count() == 0)
{

    <div class="col-md-6 col-center">
        <h1>User Roles</h1>
        <div class="row">
            <div class="col-md-12 form-group">
                <a asp-action="Add" class="btn btn-primary pull-right">Add</a>
            </div>
        </div>
        <div class="panel panel-danger">
            <div class="panel-heading">User Roles</div>
            <div class="panel-body">There are current no services added, please add at least one</div>
        </div>

    </div>
}
else
{
    <div class="row">
        <div class="col-md-6 col-center">
            <h1>User Roles</h1>

            @if (Model.Success == true)
            {
                <div class="alert alert-success">
                    <strong>Success!</strong> User successfully delete!
                </div>
            }


            <div class="row  form-group">
                <div class="col-md-12">
                    <div class="pull-right">
                        <a asp-action="Add" class="btn btn-primary">Add</a>
                    </div>
                </div>
            </div>

            <div class="">

                <table class="table">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Role</th>
                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var userRole in Model.UserRoles)
                        {
                            <tr>
                                <td>
                                    <a asp-action="Edit" asp-route-username="@userRole.UserName" asp-route-rolename="@userRole.RoleName"> @Html.DisplayFor(modelItem => userRole.UserName)</a>
                                </td>

                                <td>
                                    <a asp-action="Edit" asp-route-username="@userRole.UserName" asp-route-rolename="@userRole.RoleName"> @Html.DisplayFor(modelItem => userRole.RoleName)</a>
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>
}