Doctors/Controllers/DoctorController.cs
using Doctors.Data;
using Doctors.Models.Doctors;
using Doctors.ViewModels.DoctorViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Doctors.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;
        public DoctorController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }

        public ActionResult Index()
        {
            DoctorsListViewModel model = new DoctorsListViewModel();

            var user = User.Identity.Name;

            var loggedInUser = applicationDbContext.Users.FirstOrDefault(x => x.UserName == user);

            var doctor = applicationDbContext.Doctors.FirstOrDefault(x => x.UserId == loggedInUser.Id);

            model.Patients = applicationDbContext.Patients.Where(x => x.DoctorId == doctor.Id).ToList();

            return View(model);
        }

        public IActionResult Add()
        {
            AddDoctorViewModel model = new AddDoctorViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddDoctorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var exist = applicationDbContext.Doctors.FirstOrDefault(x => x.Name == model.Name);

                if (exist != null)
                {
                    ModelState.AddModelError("", "Sorry, Doctor already exists.");
                    return View(model);
                }

                Doctor doctor = new Doctor();

                doctor.Name = model.Name;
                doctor.Address = model.Address;
                doctor.Phone = model.Phone;

                applicationDbContext.Doctors.Add(doctor);
                applicationDbContext.SaveChanges();
            }
            else
            {
                ModelState.AddModelError("", "Form has errors");
                return View(model);
            }

            return View(model);
        }
        
    }


}

Doctors/Controllers/PatientController.cs
using Doctors.Data;
using Doctors.Models.Patients;
using Doctors.ViewModels.PatientViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;

namespace Doctors.Controllers
{
    [Authorize]
    public class PatientController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public PatientController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }


        public ActionResult Index()
        {
            PatientsListViewModel model = new PatientsListViewModel();

            model.Patients = applicationDbContext.Patients.ToList();

            return View(model);
        }


        public IActionResult Add()
        {
            AddPatientViewModel model = new AddPatientViewModel();

            var doctors = applicationDbContext.Doctors.ToList();
            model.Doctors = new SelectList(doctors, "Id", "Name");


            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddPatientViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doctors = applicationDbContext.Doctors.ToList();
                model.Doctors = new SelectList(doctors, "Id", "Name");

                var exist = applicationDbContext.Patients.FirstOrDefault(x => x.Name == model.Name);

                if (exist != null)
                {
                    ModelState.AddModelError("", "Sorry, Doctor already exists.");
                    return View(model);
                }

                Patient patient = new Patient();

                patient.Age = model.Age;
                patient.Gender = Convert.ToChar(model.Gender);
                patient.Name = model.Name;
                patient.Address = model.Address;
                patient.Phone = model.Phone;
                patient.DoctorId = Convert.ToInt32(model.DoctorId);

                applicationDbContext.Patients.Add(patient);
                applicationDbContext.SaveChanges();
            }
            else
            {
                ModelState.AddModelError("", "Form has errors");
                return View(model);
            }

            return View(model);
        }
    }
}

Doctors/Controllers/RoleController.cs
using Doctors.Data;
using Doctors.Models.Roles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MVC.ViewModels.RoleViewModels;
using System.Linq;

namespace MVC.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        private ApplicationDbContext _context;
        public RoleController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
        }

        public IActionResult Index(RoleListViewModel model, bool? success)
        {
            model.Roles = _context.Roles.AsEnumerable();
            model.Success = success;

            return View("Index", model);
        }

        public IActionResult Add()
        {
            AddRoleViewModel model = new AddRoleViewModel();
            model.Success = false;
            return View("Add", model);
        }

        [HttpPost]
        public IActionResult Add(AddRoleViewModel model)
        {

            var exists = _context.Roles.FirstOrDefault(x => x.Name == model.Name);

            if (ModelState.IsValid)
            {
                model.Success = false;
                if (exists != null)
                {
                    ModelState.AddModelError("", "Role already exists");
                    return View("Add", model);
                }
                else
                {
                    Role role = new Role();

                    role.Name = model.Name?.Trim();
                    role.NormalizedName = model.Name?.Trim().ToUpper();

                    model.Success = true;

                    _context.Roles.Add(role);
                    _context.SaveChanges();
                }

                return View("Add", model);
            }


            return View("Add", model);
        }


        public IActionResult Edit(string id)
        {
            EditRoleViewModel model = new EditRoleViewModel();
            model.Success = false;

            var role = _context.Roles.FirstOrDefault(x => x.Id == id);

            if (ModelState.IsValid)
            {
                if (role == null)
                {
                    ModelState.AddModelError("", "Role does not exist");
                    return View("Edit", model);
                }

                model.Name = role.Name;

                return View("Edit", model);
            }

            return View("Edit", model);
        }

        [HttpPost]
        public IActionResult Edit(EditRoleViewModel model, string id)
        {
            var role = _context.Roles.FirstOrDefault(x => x.Id == id);

            if (ModelState.IsValid)
            {
                if (role == null)
                {
                    ModelState.AddModelError("", "Role does not exist");
                    return View("Edit", model);
                }

                model.Success = true;

                role.Name = model.Name;

                _context.Roles.Update(role);
                _context.SaveChanges();

                return View("Edit", model);

            }
            return View("Edit", model);
        }

        public IActionResult Delete(string name)
        {
            var role = _context.Roles.FirstOrDefault(x => x.Name == name);

            if (ModelState.IsValid)
            {
                if (role == null)
                {
                    ModelState.AddModelError("", "Role does not exist");
                    return RedirectToAction("Index");
                }

                _context.Roles.Remove(role);
                _context.SaveChanges();

                return RedirectToAction("Index", new { success = true });
            }


            return RedirectToAction("Index");
        }

    }
}

Doctors/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Doctors.Data;
using Doctors.Models.Users;
using Doctors.ViewModels;
using Doctors.ViewModels.DoctorToPatientViewModels;
using Doctors.ViewModels.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Doctors.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public UserController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            UserListViewModel model = new UserListViewModel();

            model.Users = applicationDbContext.Users.ToList();

            return View(model);
        }

        public IActionResult AssignPatientToDoctor()
        {
            AssignDoctorsToPatientsViewModel model = new AssignDoctorsToPatientsViewModel();
            var doctors = applicationDbContext.Doctors.ToList();
            var patients = applicationDbContext.Patients.ToList();
            model.Doctors = new SelectList(doctors, "Id", "Name");
            model.Patients = new SelectList(patients, "Id", "Name");

            return View(model);
        }

        [HttpPost]
        public IActionResult AssignPatientToDoctor(AssignDoctorsToPatientsViewModel model)
        {
            var doctors = applicationDbContext.Doctors.ToList();
            var patients = applicationDbContext.Patients.ToList();
            model.Doctors = new SelectList(doctors, "Id", "Name");
            model.Patients = new SelectList(patients, "Id", "Name");

            var selectedDoctor = model.Doctors.Where(x => x.Value == model.DoctorId).First();
            selectedDoctor.Selected = true;

            var selectedPatient = model.Patients.Where(x => x.Value == model.PatientId).First();
            selectedPatient.Selected = true;

            if (ModelState.IsValid)
            {
                var exists = applicationDbContext.Patients.FirstOrDefault(x => x.Id == Convert.ToInt32(selectedPatient.Value) && x.DoctorId == Convert.ToInt32(selectedDoctor.Value));

                if (exists != null)
                {
                    ModelState.AddModelError("", "Sorry, Assignment already exists.");
                    return View(model);
                }

                var patient = applicationDbContext.Patients.FirstOrDefault(x => x.Id == Convert.ToInt32(selectedPatient.Value));

                patient.DoctorId = Convert.ToInt32(selectedDoctor.Value);

                applicationDbContext.Update(patient);
                applicationDbContext.SaveChanges();
            }
            return View(model);
        }

        public IActionResult Add()
        {
            AddUserViewModel model = new AddUserViewModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var exist = applicationDbContext.Users.FirstOrDefault(x => x.Email == model.Email);
                if (exist != null)
                {
                    ModelState.AddModelError("", "Sorry, User already exists.");
                    return View(model);
                }

                PasswordHasher<User> hasher = new PasswordHasher<User>();
                User user = new User();
                user.Email = model.Email;
                user.PasswordHash = hasher.HashPassword(user, model.PasswordHash);
                user.PhoneNumber = model.PhoneNumber;
                user.UserName = model.UserName;

                //saves user in the database
                applicationDbContext.Add(user);
                applicationDbContext.SaveChanges();

            }
            else
            {
                ModelState.AddModelError("", "Form has errors");
                return View(model);
            }

            return View(model);
        }

        public IActionResult Edit(string username)
        {
            EditUserViewModel model = new EditUserViewModel();

            var user = applicationDbContext.Users.FirstOrDefault(x => x.UserName == username);
            if (user == null)
            {
                ModelState.AddModelError("", "Sorry, User does not exist.");
                return View(model);
            }

            model.UserName = user.UserName;
            model.Email = user.Email;
            model.PhoneNumber = user.PhoneNumber;
            model.UserName = user.UserName;

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditUserViewModel model)
        {
            var user = applicationDbContext.Users.FirstOrDefault(x => x.UserName == model.UserName);
            if (user == null)
            {
                ModelState.AddModelError("", "Sorry, User does not exist.");
                return View(model);
            }

            user.UserName = model.UserName;
            user.Email = model.Email;
            user.PhoneNumber = model.PhoneNumber;

            //saves user in the database
            applicationDbContext.Update(user);
            applicationDbContext.SaveChanges();

            return View(model);
        }
    }
}

Doctors/Views/Shared/_AuthenticatedNav.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Doctors</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
                <li><a asp-area="" asp-controller="Role" asp-action="Index">Roles</a></li>
                <li><a asp-area="" asp-controller="UserRole" asp-action="Index">User Roles</a></li>
                <li><a asp-area="" asp-controller="Doctor" asp-action="Index">Doctors</a></li>
                <li><a asp-area="" asp-controller="Patient" asp-action="Index">Patients</a></li>
                <li><a asp-area="" asp-controller="Appointment" asp-action="Index">Appointments</a></li>
                <li><a asp-area="" asp-controller="User" asp-action="AssignPatientToDoctor">Assign Patients</a></li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</nav>
<div class="container body-content">

Doctors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Doctors</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div>

        @{
            bool isAuthenticated = User.Identity.IsAuthenticated;

            if (isAuthenticated)
            {
                @await Html.PartialAsync("_AuthenticatedNav")
            }
            else
            {

                @await Html.PartialAsync("_UnauthenticatedNav")
            }
        }

        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Doctors/Views/Shared/_UnauthenticatedNav.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Doctors</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</nav>
<div class="container body-content">